apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-server-access
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: kube-system
roleRef:
  kind: Role
  name: metrics-server-access
  apiGroup: rbac.authorization.k8s.io
