# metrics-server-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-server
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: metrics-server
  apiGroup: rbac.authorization.k8s.io
