pipeline {
    agent any
    environment {
        APP_PORT = '8010'
        DOCKER_IMAGE = 'rental-recommender/listing-service:latest'
        CONTAINER_NAME = 'listing-service-container'
    }
    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                checkout scm
            }
        }

                stage('Install Dependencies') {
            steps {
                // Install dependencies
                dir('listing-service') {
                    sh '''
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Run Tests') {
            steps {
                // Run the test cases
                dir('listing-service') {
                    sh '''
                    export PATH=$PATH:/var/lib/jenkins/.local/bin
                    pytest --version
                    pytest test_app.py --maxfail=5 --disable-warnings --verbose
                '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // Navigate to listing-service and build the Docker image
                dir('listing-service') {
                    sh '''
                    docker build -t $DOCKER_IMAGE .
                    '''
                }
            }
        }
        stage('Stop Existing Container') {
            steps {
                script {
                    // Stop and remove the existing container if it exists
                    def containerId = sh(script: "docker ps -aq --filter name=$CONTAINER_NAME", returnStdout: true).trim()
                    if (containerId) {
                        sh "docker stop ${containerId}"
                        sh "docker rm ${containerId}"
                    }
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                // Run the Docker container with the specified name and port mapping
                sh '''
                docker run -d \
                    -p $APP_PORT:$APP_PORT \
                    --name $CONTAINER_NAME \
                    $DOCKER_IMAGE
                '''
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
